version: '3'

services:
  boca-judge:
    image: vitalyx/boca-judge
    container_name: boca
    ports:
      - "8010:80"
      - "9010:9001"
    privileged: true
    environment:
      - USER=system
      - PASS=boca
